### ISSUE TITLE
Update screw up?

### ISSUE THREAD

**Issue by MtnBiker** [maptimeLA/old-la-restaurants#13]
I just tried to change two words in readme, and had just synced, but when I commited I got this message:

old-la-restaurants [master] $ git commit -m "Read me typo and one Nikki's full name"
[master 1a62d0f] Read me typo and one Nikki's full name
 7 files changed, 155 insertions(+), 1 deletion(-)
 create mode 100644 old restaurants LA from github.tm2source/.thumb.png
 create mode 100644 old restaurants LA from github.tm2source/data.xml
 create mode 100644 old restaurants LA from github.tm2source/data.yml
 create mode 100644 old restaurants LA from shp file.tm2source/.thumb.png
 create mode 100644 old restaurants LA from shp file.tm2source/data.xml
 create mode 100644 old restaurants LA from shp file.tm2source/data.yml

Sorry if I messed up something, but I thought I had an up to date copy of the repository. More to learn about git. 

Greg

**Comment by machikoyasuda** [comment]
Hi @MtnBiker - you are doing all the right things! You have not made any changes onto master on GitHub, as you can see here: https://github.com/maptimeLA/old-la-restaurants/commits/master --- your commit is not on there.

You have made changes onto your local computer's version of master, but not the public online GitHub version of master.

To do this, I would:
1. Make a branch on your computer --- gregs-branch
2. Make the commit on that branch
3. Push that branch up to GitHub

And I can accept the Pull Request and merge your changes into the public online GitHub version of master, so everyone else can pull it as well.

**Comment by MtnBiker** [comment]
Thank you. Duh. I got worried when I saw all the changes. But it was only a commit, not a push. Got what I should have done. Next time!

The main thing I was trying to do was change who’s to whose. Others were even less important.

Greg

**Comment by MtnBiker** [comment]
This issue can be closed since I really didn't mess anything up. But I don't think I can do it.
