### ISSUE TITLE
Add a Google Form for new submissions

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/old-la-restaurants#9]
What fields should we use?
Which email address?

**Comment by chanbot5000** [comment]
Question-
*An historic restaurant...
*A historic restaurant...

???

**Comment by chanbot5000** [comment]
Form: https://docs.google.com/forms/d/1CCU2e7oJlce5HpEOEse3_FHKRRA8oUzKr9yX-M1YKyg/viewform
